[build]
cmd = "go run main.go"  # Command to run the app
bin = "./tmp/main"       # Directory for binary output
exclude_dir = ["assets", "tmp", "dist"]  # Optional: exclude directories
include_ext = ["go", "tpl", "tmpl", "html"]  # Include file types to watch
delay = 1000            # Delay (in milliseconds) between changes

[log]
time = true  # Enable timestamp in logs